# LF1000 Platform Support
snd-soc-lf1000-objs := lf1000-pcm.o
snd-soc-lf1000-i2s-objs := lf1000-i2s.o

obj-$(CONFIG_SND_LF1000_SOC) += snd-soc-lf1000.o
obj-$(CONFIG_SND_LF1000_SOC_I2S) += snd-soc-lf1000-i2s.o

# LF1000 Machine Support
snd-soc-didj-cs43l22-objs := didj-cs43l22.o
snd-soc-didj-lfp100-objs := didj-lfp100.o

obj-$(CONFIG_SND_LF1000_SOC_DIDJ_CS43L22) += snd-soc-didj-cs43l22.o
obj-$(CONFIG_SND_LF1000_SOC_DIDJ_LFP100) += snd-soc-didj-lfp100.o
