/* LF1000 Display Controller (DPC) Driver 
 *
 * dpc_config.h -- Device default configuration.
 *
 * Andrey Yurovsky <andrey@cozybit.com> */

#ifndef DPC_CONFIG_H
#define DPC_CONFIG_H

#include <mach/gpio.h>

/* Dual display support for TV output on 2nd DPC */
#ifdef  CONFIG_LF1000_DPC_DUAL_DISPLAY
#define DUAL_DISPLAY			1
#endif

#if defined(CONFIG_MACH_ME_LF1000) || defined(CONFIG_MACH_LF_LF1000)
#define LCD_RESET_PORT			GPIO_PORT_ALV
#define LCD_RESET_PIN			5
#define LCD_nRESET_LEVEL		1
#else
#warning "LCD Reset Pin not set for this platform."
#define LCD_RESET_PORT			GPIO_PORT_B
#define LCD_RESET_PIN			31
#define LCD_nRESET_LEVEL		1
#endif

#define DISPLAY_VID_PRI_OUTORDER	VID_ORDER_CbYCrY
#define DISPLAY_VID_PRI_OUTPUT_FORMAT	VID_FORMAT_RGB888

/* backlight settings */
#if defined CONFIG_MACH_LF_LF1000 || defined CONFIG_MACH_ME_LF1000
#define LCD_BACKLIGHT			PWM_CHAN1
#else
#define LCD_BACKLIGHT			PWM_CHAN0
#endif
#define LCD_BACKLIGHT_PERIOD		512

/* timing and pin map */
#define NUM_PVD_PINS 24
#define DISPLAY_VID_PRI_VCLK_SOURCE		VID_VCLK_SOURCE_PLL1
#define DISPLAY_VID_PRI_VCLK2_SOURCE		VID_VCLK_SOURCE_VCLK2
#define DISPLAY_VID_PRI_SWAP_RGB		0
#define DPC_DESIRED_CLOCK_HZ			6400000
#define DISPLAY_VID_PRI_PAD_VCLK		VID_PADVCLK_nVCLK2
#define DISPLAY_VID_PRI_VCLK_DELAY		0
#define DISPLAY_VID_PRI_VCLK_INV		1
#define DISPLAY_VID_PRI_VCLK_OUT_ENB		0
#define DISPLAY_VID_PRI_VCLK2_DIV		0
#define DISPLAY_VID_PRI_MAX_X_RESOLUTION	320
#define DISPLAY_VID_PRI_MAX_Y_RESOLUTION	240
#define DISPLAY_VID_PRI_HSYNC_SWIDTH		2
#define DISPLAY_VID_PRI_HSYNC_FRONT_PORCH	50
#define DISPLAY_VID_PRI_HSYNC_BACK_PORCH	36
#define DISPLAY_VID_PRI_HSYNC_ACTIVEHIGH	0
#define DISPLAY_VID_PRI_VSYNC_SWIDTH		1
#define DISPLAY_VID_PRI_VSYNC_FRONT_PORCH	4
#define DISPLAY_VID_PRI_VSYNC_BACK_PORCH	17
#define DISPLAY_VID_PRI_VSYNC_ACTIVEHIGH	0


/* PVD Pin/Port Map */
static char pvd_pins[NUM_PVD_PINS] = {
	GPIO_PIN0, GPIO_PIN1, GPIO_PIN2, GPIO_PIN3, GPIO_PIN4, GPIO_PIN5,
	GPIO_PIN6, GPIO_PIN7, GPIO_PIN16, GPIO_PIN17, GPIO_PIN18, GPIO_PIN19,
	GPIO_PIN20, GPIO_PIN21, GPIO_PIN22, GPIO_PIN23, GPIO_PIN24,
	GPIO_PIN25, GPIO_PIN26, GPIO_PIN27, GPIO_PIN28, GPIO_PIN29, GPIO_PIN30,
	GPIO_PIN31
};

static char pvd_ports[NUM_PVD_PINS] = {
	GPIO_PORT_A, GPIO_PORT_A, GPIO_PORT_A, GPIO_PORT_A, GPIO_PORT_A,
	GPIO_PORT_A, GPIO_PORT_A, GPIO_PORT_A, GPIO_PORT_B, GPIO_PORT_B,
	GPIO_PORT_B, GPIO_PORT_B, GPIO_PORT_B, GPIO_PORT_B, GPIO_PORT_B,
	GPIO_PORT_B, GPIO_PORT_B, GPIO_PORT_B, GPIO_PORT_B, GPIO_PORT_B,
	GPIO_PORT_B, GPIO_PORT_B, GPIO_PORT_B, GPIO_PORT_B, 
};


#endif

